include_1d:
  mask: false
  origin: false
  einstein_radius: true
  half_light_radius: true
include_2d:
  mask: true
  origin: false
  border: true
  grid: false
  positions: true
  caustics: true
  critical_curves: true
  light_profile_centres: true
  mass_profile_centres: true
  multiple_images: true
  mapper_data_mesh_grid: true
  mapper_source_grid_slim: false
  mapper_source_mesh_grid: false
