Chameleon:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  core_radius_0:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  core_radius_1:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  intensity:
    type: LogUniform
    lower_limit: 0.99999
    upper_limit: 1.0000001
    width_modifier:
      type: Relative
      value: 1.0e-08
    gaussian_limits:
      lower: 0.0
      upper: inf
ChameleonSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  core_radius_0:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  core_radius_1:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
DevVaucouleurs:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  effective_radius:
    type: Uniform
    lower_limit: 0.99999
    upper_limit: 1.000001
    width_modifier:
      type: Absolute
      value: 1.0e-07
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  intensity:
    type: LogUniform
    lower_limit: 0.99999
    upper_limit: 1.0000001
    width_modifier:
      type: Relative
      value: 1.0e-08
    gaussian_limits:
      lower: 0.0
      upper: inf
DevVaucouleursSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.99999
    upper_limit: 1.000001
    width_modifier:
      type: Absolute
      value: 1.0e-07
    gaussian_limits:
      lower: 0.0
      upper: inf
Exponential:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  effective_radius:
    type: Uniform
    lower_limit: 0.99999
    upper_limit: 1.000001
    width_modifier:
      type: Absolute
      value: 1.0e-07
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  intensity:
    type: LogUniform
    lower_limit: 0.99999
    upper_limit: 1.0000001
    width_modifier:
      type: Relative
      value: 1.0e-08
    gaussian_limits:
      lower: 0.0
      upper: inf
ExponentialSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.99999
    upper_limit: 1.000001
    width_modifier:
      type: Absolute
      value: 1.0e-07
    gaussian_limits:
      lower: 0.0
      upper: inf
Gaussian:
  sigma:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 25.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  ell_comps_0:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  intensity:
    type: LogUniform
    lower_limit: 0.99999
    upper_limit: 1.0000001
    width_modifier:
      type: Relative
      value: 1.0e-08
    gaussian_limits:
      lower: 0.0
      upper: inf
GaussianSph:
  sigma:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 25.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
Point:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
PointFlux:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  flux:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
PointSourceChi:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
Sersic:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  effective_radius:
    type: Uniform
    lower_limit: 0.99999
    upper_limit: 1.000001
    width_modifier:
      type: Absolute
      value: 1.0e-07
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  intensity:
    type: LogUniform
    lower_limit: 0.99999
    upper_limit: 1.0000001
    width_modifier:
      type: Relative
      value: 1.0e-08
    gaussian_limits:
      lower: 0.0
      upper: inf
  sersic_index:
    type: Uniform
    lower_limit: 1.9999
    upper_limit: 2.0001
    width_modifier:
      type: Absolute
      value: 1.0e-06
    gaussian_limits:
      lower: 0.5
      upper: inf
SersicCore:
  alpha:
    type: Constant
    value: 3.0
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  effective_radius:
    type: Uniform
    lower_limit: 0.99999
    upper_limit: 1.000001
    width_modifier:
      type: Absolute
      value: 1.0e-07
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  gamma:
    type: Constant
    value: 0.25
  intensity:
    type: LogUniform
    lower_limit: 1.0e-05
    upper_limit: 1000.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  radius_break:
    type: Constant
    value: 0.025
  sersic_index:
    type: Uniform
    lower_limit: 1.9999
    upper_limit: 2.0001
    width_modifier:
      type: Absolute
      value: 1.0e-06
    gaussian_limits:
      lower: 0.5
      upper: inf
SersicCoreSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.99999
    upper_limit: 1.000001
    width_modifier:
      type: Absolute
      value: 1.0e-07
    gaussian_limits:
      lower: 0.0
      upper: inf
  intensity:
    type: LogUniform
    lower_limit: 1.0e-05
    upper_limit: 1000.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  sersic_index:
    type: Uniform
    lower_limit: 1.9999
    upper_limit: 2.0001
    width_modifier:
      type: Absolute
      value: 1.0e-06
    gaussian_limits:
      lower: 0.5
      upper: inf
  alpha:
    type: Constant
    value: 3.0
  gamma:
    type: Constant
    value: 0.25
  radius_break:
    type: Constant
    value: 0.025
SersicSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.99999
    upper_limit: 1.000001
    width_modifier:
      type: Absolute
      value: 1.0e-07
    gaussian_limits:
      lower: 0.0
      upper: inf
  sersic_index:
    type: Uniform
    lower_limit: 1.9999
    upper_limit: 2.0001
    width_modifier:
      type: Absolute
      value: 1.0e-06
    gaussian_limits:
      lower: 0.5
      upper: inf
