chameleon.Chameleon:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.0001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  core_radius_0:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  core_radius_1:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
  intensity:
    type: LogUniform
    lower_limit: 0.99999
    upper_limit: 1.0000001
    width_modifier:
      type: Relative
      value: 1.0e-08
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_ratio:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.3
    gaussian_limits:
      lower: 0.0
      upper: inf
chameleon.ChameleonSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  core_radius_0:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.3
    gaussian_limits:
      lower: 0.0
      upper: inf
  core_radius_1:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.3
    gaussian_limits:
      lower: 0.0
      upper: inf
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_ratio:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.3
    gaussian_limits:
      lower: 0.0
      upper: inf
dev_vaucouleurs.DevVaucouleurs:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_ratio:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
    gaussian_limits:
      lower: 0.0
      upper: inf
dev_vaucouleurs.DevVaucouleursSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_ratio:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
    gaussian_limits:
      lower: 0.0
      upper: inf
exponential.Exponential:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_ratio:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
    gaussian_limits:
      lower: 0.0
      upper: inf
exponential.ExponentialSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_ratio:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
    gaussian_limits:
      lower: 0.0
      upper: inf
gaussian.Gaussian:
  sigma:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 25.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  ell_comps_0:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
  intensity:
    type: LogUniform
    lower_limit: 0.99999
    upper_limit: 1.0000001
    width_modifier:
      type: Relative
      value: 1.0e-08
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_ratio:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
    gaussian_limits:
      lower: 0.0
      upper: inf
sersic.Sersic:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_ratio:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
    gaussian_limits:
      lower: 0.0
      upper: inf
  sersic_index:
    type: Uniform
    lower_limit: 0.8
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: 0.8
      upper: 5.0
sersic.SersicSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_ratio:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
    gaussian_limits:
      lower: 0.0
      upper: inf
  sersic_index:
    type: Uniform
    lower_limit: 0.8
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: 0.8
      upper: 5.0
sersic_core.SersicCore:
  alpha:
    type: Uniform
    lower_limit: 4.5
    upper_limit: 5.5
    width_modifier:
      type: Absolute
      value: 3.0
    gaussian_limits:
      lower: 4.5
      upper: 5.5
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
  gamma:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.5
    width_modifier:
      type: Absolute
      value: 0.1
    gaussian_limits:
      lower: 0.0
      upper: inf
  intensity:
    type: LogUniform
    lower_limit: 1.0e-05
    upper_limit: 1000.0
    width_modifier:
      type: Relative
      value: 0.2
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_ratio:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.3
    gaussian_limits:
      lower: 0.0
      upper: inf
  radius_break:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.1
    gaussian_limits:
      lower: 0.0
      upper: inf
  sersic_index:
    type: Uniform
    lower_limit: 0.8
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: 0.8
      upper: 5.0
sersic_core.SersicCoreSph:
  alpha:
    type: Uniform
    lower_limit: 4.5
    upper_limit: 5.5
    width_modifier:
      type: Absolute
      value: 3.0
    gaussian_limits:
      lower: 4.5
      upper: 5.5
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  gamma:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.5
    width_modifier:
      type: Absolute
      value: 0.1
    gaussian_limits:
      lower: 0.0
      upper: inf
  intensity:
    type: LogUniform
    lower_limit: 1.0e-05
    upper_limit: 1000.0
    width_modifier:
      type: Relative
      value: 0.2
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_ratio:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.3
    gaussian_limits:
      lower: 0.0
      upper: inf
  radius_break:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.1
    gaussian_limits:
      lower: 0.0
      upper: inf
  sersic_index:
    type: Uniform
    lower_limit: 0.8
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: 0.8
      upper: 5.0
sersic_gradient.SersicGradient:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_gradient:
    type: Uniform
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.01
    gaussian_limits:
      lower: -inf
      upper: inf
  mass_to_light_ratio:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
    gaussian_limits:
      lower: 0.0
      upper: inf
  sersic_index:
    type: Uniform
    lower_limit: 0.8
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: 0.8
      upper: 5.0
sersic_gradient.SersicGradientSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_gradient:
    type: Uniform
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.01
    gaussian_limits:
      lower: -inf
      upper: inf
  mass_to_light_ratio:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
    gaussian_limits:
      lower: 0.0
      upper: inf
  sersic_index:
    type: Uniform
    lower_limit: 0.8
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: 0.8
      upper: 5.0
