chameleon.Chameleon:
  centre_0:
    lower_limit: -inf
    mean: 0.0
    sigma: 0.0001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  centre_1:
    lower_limit: -inf
    mean: 0.0
    sigma: 0.0001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.01
  core_radius_0:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.01
  core_radius_1:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.01
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.99999
    type: LogUniform
    upper_limit: 1.0000001
    width_modifier:
      type: Relative
      value: 1.0e-08
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.3
chameleon.ChameleonSph:
  centre_0:
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  core_radius_0:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.3
  core_radius_1:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.3
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.3
dev_vaucouleurs.DevVaucouleurs:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
dev_vaucouleurs.DevVaucouleursSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
exponential.Exponential:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
exponential.ExponentialSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
gaussian.Gaussian:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.99999
    type: LogUniform
    upper_limit: 1.0000001
    width_modifier:
      type: Relative
      value: 1.0e-08
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
  sigma:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 25.0
    width_modifier:
      type: Relative
      value: 0.01
sersic.Sersic:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
  sersic_index:
    gaussian_limits:
      lower: 0.8
      upper: 5.0
    lower_limit: 0.8
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
sersic.SersicSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
  sersic_index:
    gaussian_limits:
      lower: 0.8
      upper: 5.0
    lower_limit: 0.8
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
sersic_core.SersicCore:
  alpha:
    gaussian_limits:
      lower: 4.5
      upper: 5.5
    lower_limit: 4.5
    type: Uniform
    upper_limit: 5.5
    width_modifier:
      type: Absolute
      value: 3.0
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  gamma:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.5
    width_modifier:
      type: Absolute
      value: 0.1
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-05
    type: LogUniform
    upper_limit: 1000.0
    width_modifier:
      type: Relative
      value: 0.2
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.3
  radius_break:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.1
  sersic_index:
    gaussian_limits:
      lower: 0.8
      upper: 5.0
    lower_limit: 0.8
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
sersic_core.SersicCoreSph:
  alpha:
    gaussian_limits:
      lower: 4.5
      upper: 5.5
    lower_limit: 4.5
    type: Uniform
    upper_limit: 5.5
    width_modifier:
      type: Absolute
      value: 3.0
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  gamma:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.5
    width_modifier:
      type: Absolute
      value: 0.1
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-05
    type: LogUniform
    upper_limit: 1000.0
    width_modifier:
      type: Relative
      value: 0.2
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.3
  radius_break:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.1
  sersic_index:
    gaussian_limits:
      lower: 0.8
      upper: 5.0
    lower_limit: 0.8
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
sersic_radial_gradient.SersicRadialGradient:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
  mass_to_light_gradient:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -1.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.01
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
  sersic_index:
    gaussian_limits:
      lower: 0.8
      upper: 5.0
    lower_limit: 0.8
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
sersic_radial_gradient.SersicRadialGradientSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
  mass_to_light_gradient:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -1.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.01
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
  sersic_index:
    gaussian_limits:
      lower: 0.8
      upper: 5.0
    lower_limit: 0.8
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
