isothermal.Isothermal:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  einstein_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.5999
    type: Uniform
    upper_limit: 1.6001
    width_modifier:
      type: Relative
      value: 0.0001
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
isothermal.IsothermalSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  einstein_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.5999
    type: Uniform
    upper_limit: 1.6001
    width_modifier:
      type: Relative
      value: 0.0001
isothermal_core.IsothermalCore:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  core_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.2
    width_modifier:
      type: Absolute
      value: 0.1
  einstein_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.5999
    type: Uniform
    upper_limit: 1.6001
    width_modifier:
      type: Relative
      value: 0.0001
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
isothermal_core.IsothermalCoreSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  core_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.2
    width_modifier:
      type: Absolute
      value: 0.1
  einstein_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.5999
    type: Uniform
    upper_limit: 1.6001
    width_modifier:
      type: Relative
      value: 0.0001
point.PointMass:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  einstein_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.5999
    type: Uniform
    upper_limit: 1.6001
    width_modifier:
      type: Relative
      value: 0.0001
power_law.PowerLaw:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  einstein_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.5999
    type: Uniform
    upper_limit: 1.6001
    width_modifier:
      type: Relative
      value: 0.0001
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  slope:
    gaussian_limits:
      lower: 1.999
      upper: 2.001
    lower_limit: 1.5
    type: Uniform
    upper_limit: 3.0
    width_modifier:
      type: Absolute
      value: 0.0001
power_law.PowerLawSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  einstein_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.5999
    type: Uniform
    upper_limit: 1.6001
    width_modifier:
      type: Relative
      value: 0.0001
  slope:
    gaussian_limits:
      lower: 1.999
      upper: 2.001
    lower_limit: 1.5
    type: Uniform
    upper_limit: 3.0
    width_modifier:
      type: Absolute
      value: 0.0001
power_law_broken.PowerLawBroken:
  break_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.01
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  einstein_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.5999
    type: Uniform
    upper_limit: 1.6001
    width_modifier:
      type: Relative
      value: 0.0001
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  inner_slope:
    gaussian_limits:
      lower: 0.0
      upper: 3.0
    lower_limit: 0.0
    type: Uniform
    upper_limit: 3.0
    width_modifier:
      type: Absolute
      value: 0.01
  outer_slope:
    gaussian_limits:
      lower: 0.0
      upper: 3.0
    lower_limit: 0.0
    type: Uniform
    upper_limit: 3.0
    width_modifier:
      type: Absolute
      value: 0.01
power_law_broken.PowerLawBrokenSph:
  break_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.1
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  einstein_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.5999
    type: Uniform
    upper_limit: 1.6001
    width_modifier:
      type: Relative
      value: 0.0001
  inner_slope:
    gaussian_limits:
      lower: 0.0
      upper: 3.0
    lower_limit: 0.0
    type: Uniform
    upper_limit: 3.0
    width_modifier:
      type: Absolute
      value: 0.01
  outer_slope:
    gaussian_limits:
      lower: 0.0
      upper: 3.0
    lower_limit: 0.0
    type: Uniform
    upper_limit: 3.0
    width_modifier:
      type: Absolute
      value: 0.01
power_law_core.PowerLawCore:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  core_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.2
    width_modifier:
      type: Absolute
      value: 0.1
  einstein_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.5999
    type: Uniform
    upper_limit: 1.6001
    width_modifier:
      type: Relative
      value: 0.0001
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -0.001
    type: Uniform
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
  slope:
    gaussian_limits:
      lower: 1.999
      upper: 2.001
    lower_limit: 1.5
    type: Uniform
    upper_limit: 3.0
    width_modifier:
      type: Absolute
      value: 0.0001
power_law_core.PowerLawCoreSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.001
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
  core_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.2
    width_modifier:
      type: Absolute
      value: 0.1
  einstein_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.5999
    type: Uniform
    upper_limit: 1.6001
    width_modifier:
      type: Relative
      value: 0.0001
  slope:
    gaussian_limits:
      lower: 1.999
      upper: 2.001
    lower_limit: 1.5
    type: Uniform
    upper_limit: 3.0
    width_modifier:
      type: Absolute
      value: 0.0001
