PointMass:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  einstein_radius:
    type: Uniform
    lower_limit: 1.5999
    upper_limit: 1.6001
    width_modifier:
      type: Relative
      value: 0.0001
    gaussian_limits:
      lower: 0.0
      upper: inf
