HyperGalaxy:
  contribution_factor:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0e-08
    width_modifier:
      type: Relative
      value: 0.01
  noise_factor:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0
    type: Uniform
    upper_limit: 8.000001
    width_modifier:
      type: Relative
      value: 0.01
  noise_power:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: 0.999
    type: Uniform
    upper_limit: 1.0001
    width_modifier:
      type: Relative
      value: 0.01
