general:
  general:
    backend: default
    imshow_origin: upper
    zoom_around_mask: false
  units:
    in_kpc: false
include:
  include_2d:
    border: false
    tangential_caustics: false
    radial_caustics: false
    tangential_critical_curves: false
    radial_critical_curves: false
    grid: false
    light_profile_centres: false
    mapper_image_plane_mesh_grid: false
    mapper_source_plane_data_grid: false
    mapper_source_plane_mesh_grid: false
    mask: false
    mass_profile_centres: false
    multiple_images: false
    origin: false
    positions: false
mat_wrap:
  Axis:
    figure: {}
    subplot: {}
  Cmap:
    figure:
      cmap: default
      linscale: 0.01
      linthresh: 0.05
      norm: linear
      vmax: null
      vmin: null
    subplot:
      cmap: default
      linscale: 0.01
      linthresh: 0.05
      norm: linear
      vmax: null
      vmin: null
  Colorbar:
    figure:
      fraction: 0.047
      pad: 0.01
    subplot:
      fraction: 0.047
      pad: 0.01
  ColorbarTickParams:
    figure:
      labelsize: 10
    subplot:
      labelsize: 10
  Figure:
    figure:
      aspect: square
      figsize: (7,7)
    subplot:
      aspect: square
      figsize: auto
  Legend:
    figure:
      fontsize: 12
    subplot:
      fontsize: 12
  TickParams:
    figure:
      labelsize: 16
    subplot:
      labelsize: 10
  Title:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  XLabel:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  XTicks:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  YLabel:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  YTicks:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
mat_wrap_1d:
  AXVLine:
    figure: {}
    subplot: {}
  LinePlot:
    figure:
      c: k
    subplot:
      c: k
mat_wrap_2d:
  ArrayOverlay:
    figure:
      alpha: 0.5
    subplot:
      alpha: 0.5
  BorderScatter:
    figure:
      c: r
      marker: .
      s: 30
    subplot:
      c: r
      marker: .
      s: 30
  CausticsPlot:
    figure:
      c: k,r,g,b,m,y
      linestyle: '-'
      linewidth: 2
    subplot:
      c: k,r,g,b,m,y
      linestyle: '-'
      linewidth: 2
  CriticalCurvesPlot:
    figure:
      c: k,r,g,b,m,y
      linestyle: '-'
      linewidth: 2
    subplot:
      c: k,r,g,b,m,y
      linestyle: '-'
      linewidth: 2
  GridPlot:
    figure:
      c: k
    subplot:
      c: k
  GridScatter:
    figure:
      c: k
      marker: .
      s: 1
    subplot:
      c: k
      marker: .
      s: 1
  IndexScatter:
    figure:
      c: r,g,b,m,y,k
      marker: .
      s: 20
    subplot:
      c: r,g,b,m,y,k
      marker: .
      s: 20
  LightProfileCentresScatter:
    figure:
      c: k,r,g,b,m,y
      marker: +
      s: 20
    subplot:
      c: r,g,b,m,y,k
      marker: +
      s: 26
  MaskScatter:
    figure:
      c: k
      marker: x
      s: 10
    subplot:
      c: k
      marker: x
      s: 10
  MassProfileCentresScatter:
    figure:
      c: k,r,g,b,m,y
      marker: x
      s: 20
    subplot:
      c: r,g,b,m,y,k
      marker: x
      s: 26
  MultipleImagesScatter:
    figure:
      c: k,r,g,b,m,y
      marker: o
      s: 16
    subplot:
      c: r,g,b,m,y,k
      marker: o
      s: 16
  OriginScatter:
    figure:
      c: k
      marker: x
      s: 80
    subplot:
      c: k
      marker: x
      s: 80
  PatchOverlay:
    figure:
      edgecolor: c
      facecolor: null
    subplot:
      edgecolor: c
      facecolor: null
  PixelizationGridScatter:
    figure:
      c: c
      marker: .
      s: 1
    subplot:
      c: c
      marker: .
      s: 1
  PositionsScatter:
    figure:
      c: k,m,y,b,r,g
      marker: .
      s: 16
    subplot:
      c: k,m,y,b,r,g
      marker: .
      s: 16
  VectorFieldQuiver:
    figure:
      alpha: 1.0
      angles: xy
      headlength: 0
      headwidth: 1
      linewidth: 5
      pivot: middle
      units: xy
    subplot:
      alpha: 1.0
      angles: xy
      headlength: 0
      headwidth: 1
      linewidth: 5
      pivot: middle
      units: xy
  VoronoiDrawer:
    figure:
      alpha: 0.7
      edgecolor: k
      linewidth: 0.3
    subplot:
      alpha: 0.7
      edgecolor: k
      linewidth: 0.3
plots:
  dataset:
    absolute_signal_to_noise_map: true
    data: true
    inverse_noise_map: true
    noise_map: true
    potential_chi_squared_map: true
    signal_to_noise_map: true
    subplot_dataset: true
  fit:
    all_at_end_fits: true
    all_at_end_png: true
    chi_squared_map: true
    data: true
    model_data: true
    model_images_of_planes: true
    noise_map: true
    normalized_residual_map: true
    plane_images_of_planes: true
    residual_map: true
    signal_to_noise_map: true
    subplot_fit: true
    subplots_of_planes: true
    subtracted_images_of_planes: true
  fit_imaging: {}
  fit_interferometer:
    amplitudes_vs_uv_distances: true
    dirty_chi_squared_map: true
    dirty_image: true
    dirty_noise_map: true
    dirty_normalized_residual_map: true
    dirty_residual_map: true
    dirty_signal_to_noise_map: true
    phases_vs_uv_distances: true
    uv_wavelengths: true
  fit_quantity:
    all_at_end_fits: true
    all_at_end_png: true
    chi_squared_map: true
    image: true
    model_image: true
    noise_map: true
    normalized_residual_map: true
    residual_map: true
    subplot_fit: true
  galaxies:
    convergence: true
    image: true
    potential: true
  adapt:
    contribution_map_list: true
    images_of_galaxies: true
    model_image: true
  imaging:
    psf: true
  interferometer:
    amplitudes_vs_uv_distances: true
    dirty_image: true
    dirty_noise_map: true
    dirty_signal_to_noise_map: true
    phases_vs_uv_distances: true
    uv_wavelengths: true
  inversion:
    all_at_end_png: true
    chi_squared_map: true
    errors: true
    normalized_residual_map: true
    reconstructed_image: true
    reconstruction: true
    regularization_weights: true
    residual_map: true
    subplot_pixelization: true
  other:
    stochastic_histogram: true
  positions:
    image_with_positions: true
  tracer:
    all_at_end_fits: true
    all_at_end_png: true
    convergence: true
    deflections: true
    image: true
    magnification: true
    potential: true
    source_plane_image: true
    subplot_galaxies_images: true
    subplot_tracer: true
plots_search:
  dynesty:
    corner: true
    cornerpoints: true
    runplot: true
    traceplot: true
  emcee:
    corner: true
    likelihood_series: true
    time_series: true
    trajectories: true
  pyswarms:
    contour: true
    cost_history: true
    time_series: true
    trajectories: true
  ultranest:
    corner: true
    runplot: true
    traceplot: true
  zeus:
    corner: true
    likelihood_series: true
    time_series: true
    trajectories: true
