include_1d:
  mask: true
  origin: true
  einstein_radius: true
  half_light_radius: true
include_2d:
  mask: true
  origin: true
  border: true
  grid: true
  positions: true
  tangential_critical_curves: true
  tangential_caustics: true
  radial_critical_curves: true
  radial_caustics: true
  light_profile_centres: true
  mass_profile_centres: true
  multiple_images: true
  mapper_image_plane_mesh_grid: true
  mapper_source_plane_data_grid: true
  mapper_source_plane_mesh_grid: true
