#!/bin/bash -l

#SBATCH -N 1
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=8
#SBATCH -J stochastic
#SBATCH -o output/output.%A.out
#SBATCH -e error/error.%A.err
#SBATCH -p skylake
#SBATCH -A DIRAC-DP195-CPU
#SBATCH -t 12:00:00   # longest job
#SBATCH --mem=182gb
#SBATCH --mail-type=END                      # notifications for job done & fail
#SBATCH --mail-user=james.w.nightingale@durham.ac.uk

source /home/dc-nigh1/stochastic/activate.sh
export THREADS=8

export OPENBLAS_NUM_THREADS=$THREADS
export MKL_NUM_THREADS=$THREADS
export OMP_NUM_THREADS=$THREADS
export VECLIB_MAXIMUM_THREADS=$THREADS
export NUMEXPR_NUM_THREADS=$THREADS

srun -n 4 --multi-prog stochastic.conf
