GridSearch:
  general:
    number_of_cores: 1
    step_size: 0.1
mcmc:
  Emcee:
    auto_correlations:
      change_threshold: 0.01
      check_for_convergence: true
      check_size: 100
      required_length: 50
    initialize:
      ball_lower_limit: 0.49
      ball_upper_limit: 0.51
      method: ball
    parallel:
      number_of_cores: 1
    printing:
      silence: false
    run:
      nsteps: 2000
    search:
      nwalkers: 50
    updates:
      iterations_per_update: 2500
      remove_state_files_at_end: true
  Zeus:
    auto_correlations:
      change_threshold: 0.01
      check_for_convergence: true
      check_size: 100
      required_length: 50
    initialize:
      ball_lower_limit: 0.49
      ball_upper_limit: 0.51
      method: ball
    parallel:
      number_of_cores: 1
    printing:
      silence: false
    run:
      check_walkers: true
      light_mode: false
      maxiter: 10000
      maxsteps: 10000
      mu: 1.0
      nsteps: 2000
      patience: 5
      shuffle_ensemble: true
      tolerance: 0.05
      tune: true
      vectorize: false
    search:
      nwalkers: 50
    updates:
      iterations_per_update: 500
    remove_state_files_at_end: true
nest:
  DynestyDynamic:
    initialize:
      method: prior
    parallel:
      force_x1_cpu: false
      number_of_cores: 1
    printing:
      silence: false
    run:
      dlogz_init: 0.01
      logl_max_init: .inf
      maxcall: null
      maxcall_init: null
      maxiter: null
      maxiter_init: null
      n_effective: .inf
      n_effective_init: .inf
      nlive_init: 500
    search:
      bootstrap: null
      bound: multi
      enlarge: null
      facc: 0.2
      first_update: null
      fmove: 0.9
      max_move: 100
      sample: rwalk
      slices: 5
      update_interval: null
      walks: 5
    updates:
      iterations_per_update: 2500
      remove_state_files_at_end: true
  DynestyStatic:
    initialize:
      method: prior
    parallel:
      force_x1_cpu: false
      number_of_cores: 1
    printing:
      silence: false
    run:
      dlogz: null
      logl_max: .inf
      maxcall: null
      maxiter: null
      n_effective: null
    search:
      bootstrap: null
      bound: multi
      enlarge: null
      facc: 0.2
      first_update: null
      fmove: 0.9
      max_move: 100
      nlive: 50
      sample: rwalk
      slices: 5
      update_interval: null
      walks: 5
    updates:
      iterations_per_update: 5000
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
mle:
  Drawer:
    initialize:
      ball_lower_limit: 0.49
      ball_upper_limit: 0.51
      method: ball
    printing:
      silence: false
    search:
      total_draws: 50
    updates:
      iterations_per_update: 500
    remove_state_files_at_end: true
  PySwarmsGlobal:
    initialize:
      ball_lower_limit: 0.49
      ball_upper_limit: 0.51
      method: ball
    parallel:
      number_of_cores: 1
    printing:
      silence: false
    run:
      iters: 2000
    search:
      cognitive: 0.5
      ftol: -.inf
      inertia: 0.9
      n_particles: 50
      social: 0.3
    updates:
      iterations_per_update: 2500
      remove_state_files_at_end: true
  PySwarmsLocal:
    initialize:
      ball_lower_limit: 0.49
      ball_upper_limit: 0.51
      method: ball
    parallel:
      number_of_cores: 1
    printing:
      silence: false
    run:
      iters: 2000
    search:
      cognitive: 0.5
      ftol: -.inf
      inertia: 0.9
      minkowski_p_norm: 2
      n_particles: 50
      number_of_k_neighbors: 3
      social: 0.3
    updates:
      iterations_per_update: 500
    remove_state_files_at_end: true
