general:
  analysis:
    n_cores: 1
    preload_attempts: 250
  fits:
    flip_for_ds9: true
  grid:
    remove_projected_centre: false
  hpc:
    hpc_mode: true
    iterations_per_update: 10000
  adapt:
    adapt_minimum_percent: 0.01
    adapt_noise_limit: 100000000.0
    stochastic_outputs: false
  inversion:
    interpolated_grid_shape: image_grid
  model:
    ignore_prior_limits: false
  numba:
    cache: true
    nopython: true
    parallel: false
    use_numba: true
  output:
    force_pickle_overwrite: true
    info_whitespace_length: 80
    log_file: output.log
    log_level: INFO
    log_to_file: false
    model_results_decimal_places: 3
    remove_files: false
    samples_to_csv: true
  profiling:
    parallel_profile: false
    repeats: 1
    should_profile: false
  test:
    check_likelihood_function: false
    bypass_figure_of_merit_sanity: false
    check_preloads: false
    preloads_check_threshold: 1.0     # If the figure of merit of a fit with and without preloads is greater than this threshold, the check preload test fails and an exception raised for a model-fit.
    disable_positions_lh_inversion_check: true
  w_tilde:
    snr_cut_iteration: false
    snr_cut_start: 1.0e-10
logging:
  disable_existing_loggers: false
  formatters:
    formatter:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: formatter
      level: INFO
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      filename: root.log
      formatter: formatter
      level: INFO
  root:
    handlers:
    - console
    - file
    level: INFO
  version: 1
non_linear:
  GridSearch:
    general:
      number_of_cores: 1
      step_size: 0.1
  mcmc:
    Emcee:
      auto_correlations:
        change_threshold: 0.01
        check_for_convergence: true
        check_size: 100
        required_length: 50
      initialize:
        ball_lower_limit: 0.49
        ball_upper_limit: 0.51
        method: ball
      parallel:
        number_of_cores: 1
      printing:
        silence: false
      run:
        nsteps: 2000
      search:
        nwalkers: 50
      updates:
      iterations_per_update: 2500
      remove_state_files_at_end: true
    Zeus:
      auto_correlations:
        change_threshold: 0.01
        check_for_convergence: true
        check_size: 100
        required_length: 50
      initialize:
        ball_lower_limit: 0.49
        ball_upper_limit: 0.51
        method: ball
      parallel:
        number_of_cores: 1
      printing:
        silence: false
      run:
        check_walkers: true
        light_mode: false
        maxiter: 10000
        maxsteps: 10000
        mu: 1.0
        nsteps: 2000
        patience: 5
        shuffle_ensemble: true
        tolerance: 0.05
        tune: true
        vectorize: false
      search:
        nwalkers: 50
      updates:
        iterations_per_update: 500
    remove_state_files_at_end: true
  nest:
    DynestyDynamic:
      initialize:
        method: prior
      parallel:
        force_x1_cpu: false
        number_of_cores: 1
      printing:
        silence: false
      run:
        dlogz_init: 0.01
        logl_max_init: .inf
        maxcall: null
        maxcall_init: null
        maxiter: null
        maxiter_init: null
        n_effective: .inf
        n_effective_init: .inf
        nlive_init: 500
      search:
        bootstrap: null
        bound: multi
        enlarge: null
        facc: 0.2
        first_update: null
        fmove: 0.9
        max_move: 100
        sample: rwalk
        slices: 5
        update_interval: null
        walks: 5
      updates:
      iterations_per_update: 2500
      remove_state_files_at_end: true
    DynestyStatic:
      initialize:
        method: prior
      parallel:
        force_x1_cpu: false
        number_of_cores: 1
      printing:
        silence: false
      run:
        dlogz: null
        logl_max: .inf
        maxcall: null
        maxiter: null
        n_effective: null
      search:
        bootstrap: null
        bound: multi
        enlarge: null
        facc: 0.2
        first_update: null
        fmove: 0.9
        max_move: 100
        nlive: 50
        sample: rwalk
        slices: 5
        update_interval: null
        walks: 5
      updates:
        iterations_per_update: 5000
        log_every_update: 1
        model_results_every_update: 1
        remove_state_files_at_end: true
        visualize_every_update: 1
    UltraNest:
      initialize:
        method: prior
      parallel:
        number_of_cores: 1
      printing:
        silence: false
      run:
        Lepsilon: 0.001
        cluster_num_live_points: 40
        dKL: 0.5
        dlogz: 0.5
        frac_remain: 0.01
        insertion_test_window: 10
        insertion_test_zscore_threshold: 2
        log_interval: null
        max_iters: null
        max_ncalls: null
        max_num_improvement_loops: -1.0
        min_ess: 400
        min_num_live_points: 400
        show_status: true
        update_interval_ncall: null
        update_interval_volume_fraction: 0.8
        viz_callback: auto
      search:
        draw_multiple: true
        ndraw_max: 65536
        ndraw_min: 128
        num_bootstraps: 30
        num_test_samples: 2
        resume: true
        run_num: null
        storage_backend: hdf5
        vectorized: false
        warmstart_max_tau: -1.0
      stepsampler:
        adaptive_nsteps: false
        log: false
        max_nsteps: 1000
        nsteps: 5
        region_filter: false
        scale: 1.0
        stepsampler_cls: null
      updates:
        iterations_per_update: 5000
        log_every_update: 1
        model_results_every_update: 1
        remove_state_files_at_end: true
        visualize_every_update: 1
  optimize:
    DownhillSimplex:
      search:
        disp: 1
        ftol: 0.0001
        full_output: 0
        maxfun: null
        maxiter: null
        retall: 0
        xtol: 0.0001
    Drawer:
      initialize:
        ball_lower_limit: 0.49
        ball_upper_limit: 0.51
        method: ball
      printing:
        silence: false
      search:
        total_draws: 50
      updates:
        iterations_per_update: 500
    remove_state_files_at_end: true
    PySwarmsGlobal:
      initialize:
        ball_lower_limit: 0.49
        ball_upper_limit: 0.51
        method: ball
      parallel:
        number_of_cores: 1
      printing:
        silence: false
      run:
        iters: 2000
      search:
        cognitive: 0.5
        ftol: -.inf
        inertia: 0.9
        n_particles: 50
        social: 0.3
      updates:
      iterations_per_update: 2500
      remove_state_files_at_end: true
    PySwarmsLocal:
      initialize:
        ball_lower_limit: 0.49
        ball_upper_limit: 0.51
        method: ball
      parallel:
        number_of_cores: 1
      printing:
        silence: false
      run:
        iters: 2000
      search:
        cognitive: 0.5
        ftol: -.inf
        inertia: 0.9
        minkowski_p_norm: 2
        n_particles: 50
        number_of_k_neighbors: 3
        social: 0.3
      updates:
        iterations_per_update: 500
    remove_state_files_at_end: true
visualize:
  general:
    general:
      backend: default
      imshow_origin: upper
      zoom_around_mask: true
    units:
      in_kpc: false
  include:
    include_1d:
      einstein_radius: true
      half_light_radius: true
    include_2d:
      border: true
      tangential_caustics: true
      radial_caustics: true
      tangential_critical_curves: true
      radial_critical_curves: true
      grid: false
      light_profile_centres: true
      mapper_image_plane_mesh_grid: false
      mapper_source_plane_data_grid: false
      mapper_source_plane_mesh_grid: false
      mask: true
      mass_profile_centres: true
      multiple_images: false
      origin: false
      positions: true
  mat_wrap:
    Axis:
      figure: {}
      subplot: {}
    Cmap:
      figure:
        cmap: default
        linscale: 0.01
        linthresh: 0.05
        norm: linear
        vmax: null
        vmin: null
      subplot:
        cmap: default
        linscale: 0.01
        linthresh: 0.05
        norm: linear
        vmax: null
        vmin: null
    Colorbar:
      figure:
        fraction: 0.047
        pad: 0.01
      subplot:
        fraction: 0.047
        pad: 0.01
    ColorbarTickParams:
      figure:
        labelsize: 10
      subplot:
        labelsize: 10
    Figure:
      figure:
        aspect: square
        figsize: (7,7)
      subplot:
        aspect: square
        figsize: auto
    Legend:
      figure:
        fontsize: 12
        include_2d: true
      subplot:
        fontsize: 12
        include_2d: true
    TickParams:
      figure:
        labelsize: 16
      subplot:
        labelsize: 10
    Title:
      figure:
        fontsize: 16
      subplot:
        fontsize: 10
    XLabel:
      figure:
        fontsize: 16
      subplot:
        fontsize: 10
    XTicks:
      figure:
        fontsize: 16
      subplot:
        fontsize: 10
    YLabel:
      figure:
        fontsize: 16
      subplot:
        fontsize: 10
    YTicks:
      figure:
        fontsize: 16
      subplot:
        fontsize: 10
  mat_wrap_1d:
    AXVLine:
      figure: {}
      subplot: {}
    EinsteinRadiusAXVLine:
      figure: {}
      subplot: {}
    HalfLightRadiusAXVLine:
      figure: {}
      subplot: {}
    LinePlot:
      figure:
        c: k
      subplot:
        c: k
    YXPlot:
      figure:
        c: k
      subplot:
        c: k
  mat_wrap_2d:
    ArrayOverlay:
      figure:
        alpha: 0.5
      subplot:
        alpha: 0.5
    BorderScatter:
      figure:
        c: r
        marker: .
        s: 30
      subplot:
        c: r
        marker: .
        s: 30
    CausticsPlot:
      figure:
        c: k,r,g,b,m,y
        linestyle: '-'
        linewidth: 2
      subplot:
        c: k,r,g,b,m,y
        linestyle: '-'
        linewidth: 2
    CriticalCurvesPlot:
      figure:
        c: k,r,g,b,m,y
        linestyle: '-'
        linewidth: 2
      subplot:
        c: k,r,g,b,m,y
        linestyle: '-'
        linewidth: 2
    GridPlot:
      figure:
        c: k
      subplot:
        c: k
    GridScatter:
      figure:
        c: k
        marker: .
        s: 1
      subplot:
        c: k
        marker: .
        s: 1
    IndexScatter:
      figure:
        c: r,g,b,m,y,k
        marker: .
        s: 20
      subplot:
        c: r,g,b,m,y,k
        marker: .
        s: 20
    LightProfileCentresScatter:
      figure:
        c: k,r,g,b,m,y
        marker: +
        s: 20
      subplot:
        c: r,g,b,m,y,k
        marker: +
        s: 26
    MaskScatter:
      figure:
        c: k
        marker: x
        s: 10
      subplot:
        c: k
        marker: x
        s: 10
    MassProfileCentresScatter:
      figure:
        c: k,r,g,b,m,y
        marker: x
        s: 20
      subplot:
        c: r,g,b,m,y,k
        marker: x
        s: 26
    MultipleImagesScatter:
      figure:
        c: k,r,g,b,m,y
        marker: o
        s: 16
      subplot:
        c: r,g,b,m,y,k
        marker: o
        s: 16
    OriginScatter:
      figure:
        c: k
        marker: x
        s: 80
      subplot:
        c: k
        marker: x
        s: 80
    PatchOverlay:
      figure:
        edgecolor: c
        facecolor: null
      subplot:
        edgecolor: c
        facecolor: null
    PixelizationGridScatter:
      figure:
        c: c
        marker: .
        s: 1
      subplot:
        c: c
        marker: .
        s: 1
    PositionsScatter:
      figure:
        c: k,m,y,b,r,g
        marker: '*'
        s: 80
      subplot:
        c: k,m,y,b,r,g
        marker: '*'
        s: 80
    VectorFieldQuiver:
      figure:
        alpha: 1.0
        angles: xy
        headlength: 0
        headwidth: 1
        linewidth: 5
        pivot: middle
        units: xy
      subplot:
        alpha: 1.0
        angles: xy
        headlength: 0
        headwidth: 1
        linewidth: 5
        pivot: middle
        units: xy
    VoronoiDrawer:
      figure:
        alpha: 0.7
        edgecolor: k
        linewidth: 0.3
      subplot:
        alpha: 0.7
        edgecolor: k
        linewidth: 0.3
  plots:
    dataset:
      absolute_signal_to_noise_map: false
      data: false
      inverse_noise_map: false
      noise_map: false
      potential_chi_squared_map: false
      psf: false
      signal_to_noise_map: false
      subplot_dataset: true
      uv_wavelengths: false
    fit:
      all_at_end_fits: false
      all_at_end_png: false
      chi_squared_map: false
      data: false
      model_data: false
      model_images_of_planes: false
      noise_map: false
      normalized_residual_map: false
      plane_images_of_planes: false
      residual_map: false
      signal_to_noise_map: false
      subplot_fit: true
      subplots_of_planes: true
      subtracted_images_of_planes: false
    fit_quantity:
      all_at_end_fits: false
      all_at_end_png: false
      chi_squared_map: false
      image: false
      model_image: true
      noise_map: false
      normalized_residual_map: false
      residual_map: false
      subplot_fit: true
    adapt:
      contribution_map_list: false
      fit_no_adapt: true
      images_of_galaxies: true
      model_image: true
    inversion:
      all_at_end_png: false
      chi_squared_map: false
      errors: false
      interpolated_errors: false
      interpolated_reconstruction: false
      normalized_residual_map: false
      reconstructed_image: false
      reconstruction: true
      regularization_weight_list: false
      residual_map: false
      subplot_inversion: true
    other:
      stochastic_histogram: false
    positions:
      image_with_positions: true
    tracer:
      all_at_end_fits: false
      all_at_end_png: false
      convergence: false
      deflections: false
      image: false
      magnification: false
      potential: false
      source_plane_image: false
      subplot_galaxies_images: false
      subplot_tracer: true
    samples:
      corner: true
      progress: false
  plots_search:
    dynesty:
      corner: true
      cornerpoints: false
      runplot: true
      traceplot: true
    emcee:
      corner: true
      likelihood_series: true
      time_series: true
      trajectories: true
    pyswarms:
      contour: true
      cost_history: true
      time_series: true
      trajectories: true
    ultranest:
      corner: true
      runplot: true
      traceplot: true
    zeus:
      corner: true
      likelihood_series: true
      time_series: true
      trajectories: true
