#!/bin/bash -l

#SBATCH -J model_inversion
#SBATCH -n 1
#SBATCH --cpus-per-task=32
#SBATCH -o output/output.%A.out
#SBATCH -e error/error.%A.err
#SBATCH -p skylake
#SBATCH -A DIRAC-DP195-CPU
#SBATCH -t 0:30:00   # longest job
#SBATCH --mem=182gb
#SBATCH --mail-type=END                      # notifications for job done & fail
#SBATCH --mail-user=james.w.nightingale@durham.ac.uk

source /home/dc-nigh1/slacs/activate.sh

export THREADS=1

export OPENBLAS_NUM_THREADS=$THREADS
export MKL_NUM_THREADS=$THREADS
# export OMP_NUM_THREADS=$THREADS
export VECLIB_MAXIMUM_THREADS=$THREADS
export NUMEXPR_NUM_THREADS=$THREADS

python3 /home/dc-nigh1/profiling/model_inversion_magnification_cosma.py 32