GridSearch:
  general:
    number_of_cores: 1
    step_size: 0.1
mcmc:
  Emcee:
    auto_correlations:
      change_threshold: 0.01
      check_for_convergence: true
      check_size: 100
      required_length: 50
    initialize:
      ball_lower_limit: 0.49
      ball_upper_limit: 0.51
      method: ball
    parallel:
      number_of_cores: 1
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    run:
      nsteps: 2000
    search:
      nwalkers: 50
    updates:
      iterations_per_update: 2500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
  Zeus:
    auto_correlations:
      change_threshold: 0.01
      check_for_convergence: true
      check_size: 100
      required_length: 50
    initialize:
      ball_lower_limit: 0.49
      ball_upper_limit: 0.51
      method: ball
    parallel:
      number_of_cores: 1
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    run:
      check_walkers: true
      light_mode: false
      maxiter: 10000
      maxsteps: 10000
      mu: 1.0
      nsteps: 2000
      patience: 5
      shuffle_ensemble: true
      tolerance: 0.05
      tune: true
      vectorize: false
    search:
      nwalkers: 50
    updates:
      iterations_per_update: 500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
nest:
  DynestyDynamic:
    initialize:
      method: prior
    parallel:
      force_x1_cpu: false
      number_of_cores: 1
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    run:
      dlogz_init: 0.01
      logl_max_init: .inf
      maxcall: null
      maxcall_init: null
      maxiter: null
      maxiter_init: null
      n_effective: .inf
      n_effective_init: .inf
      nlive_init: 500
    search:
      bootstrap: null
      bound: multi
      enlarge: null
      facc: 0.5
      first_update: null
      fmove: 0.9
      max_move: 100
      sample: rwalk
      slices: 5
      update_interval: null
      walks: 5
    updates:
      iterations_per_update: 2500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
  DynestyStatic:
    initialize:
      method: prior
    parallel:
      force_x1_cpu: false
      number_of_cores: 1
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    run:
      dlogz: null
      logl_max: .inf
      maxcall: null
      maxiter: null
      n_effective: null
    search:
      bootstrap: null
      bound: multi
      enlarge: null
      facc: 0.2
      first_update: null
      fmove: 0.9
      max_move: 0
      nlive: 50
      sample: rwalk
      slices: 5
      update_interval: null
      walks: 5
    updates:
      iterations_per_update: 2500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
  MultiNest:
    initialize:
      method: prior
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    search:
      const_efficiency_mode: false
      dlogz: 0.5
      facc: 0.2
      importance_nested_sampling: false
      max_iter: 0
      max_modes: 100
      mode_tolerance: -1.0e+90
      multimodal: false
      nlive: 50
    settings:
      context: 0
      init_MPI: false
      log_zero: -1.0e+100
      n_iter_before_update: 5
      null_log_evidence: -1.0e+90
      resume: true
      seed: 0
      stagger_resampling_likelihood: false
      verbose: false
      write_output: true
    updates:
      iterations_per_update: 2500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      should_update_sym: 250
      visualize_every_update: 1
  UltraNest:
    initialize:
      method: prior
    parallel:
      number_of_cores: 1
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    run:
      Lepsilon: 0.001
      cluster_num_live_points: 40
      dKL: 0.5
      dlogz: 0.5
      frac_remain: 0.01
      insertion_test_window: 10
      insertion_test_zscore_threshold: 2
      log_interval: null
      max_iters: null
      max_ncalls: null
      max_num_improvement_loops: -1.0
      min_ess: 400
      min_num_live_points: 400
      show_status: true
      update_interval_ncall: null
      update_interval_volume_fraction: 0.8
      viz_callback: auto
    search:
      draw_multiple: true
      ndraw_max: 65536
      ndraw_min: 128
      num_bootstraps: 30
      num_test_samples: 2
      resume: true
      run_num: null
      storage_backend: hdf5
      vectorized: false
      warmstart_max_tau: -1.0
    stepsampler:
      adaptive_nsteps: false
      log: false
      max_nsteps: 1000
      nsteps: 5
      region_filter: false
      scale: 1.0
      stepsampler_cls: null
    updates:
      iterations_per_update: 5000
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
optimize:
  DownhillSimplex:
    search:
      disp: 1
      ftol: 0.0001
      full_output: 0
      maxfun: null
      maxiter: null
      retall: 0
      xtol: 0.0001
  Drawer:
    initialize:
      ball_lower_limit: 0.49
      ball_upper_limit: 0.51
      method: ball
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    search:
      total_draws: 50
    updates:
      iterations_per_update: 500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
  PySwarmsGlobal:
    initialize:
      ball_lower_limit: 0.49
      ball_upper_limit: 0.51
      method: ball
    parallel:
      number_of_cores: 1
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    run:
      iters: 2000
    search:
      cognitive: 0.5
      ftol: -.inf
      inertia: 0.9
      n_particles: 50
      social: 0.3
    updates:
      iterations_per_update: 2500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
  PySwarmsLocal:
    initialize:
      ball_lower_limit: 0.49
      ball_upper_limit: 0.51
      method: ball
    parallel:
      number_of_cores: 1
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    run:
      iters: 2000
    search:
      cognitive: 0.5
      ftol: -.inf
      inertia: 0.9
      minkowski_p_norm: 2
      n_particles: 50
      number_of_k_neighbors: 3
      social: 0.3
    updates:
      iterations_per_update: 500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
