SersicGradient:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -0.001
    upper_limit: 0.001
    width_modifier:
      type: Absolute
      value: 1.0e-05
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_gradient:
    type: Uniform
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.01
    gaussian_limits:
      lower: -inf
      upper: inf
  mass_to_light_ratio:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
    gaussian_limits:
      lower: 0.0
      upper: inf
  sersic_index:
    type: Uniform
    lower_limit: 0.8
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: 0.8
      upper: 5.0
.SersicGradientSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.001
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.0001
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.01
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_to_light_gradient:
    type: Uniform
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.01
    gaussian_limits:
      lower: -inf
      upper: inf
  mass_to_light_ratio:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.6
    width_modifier:
      type: Relative
      value: 0.0001
    gaussian_limits:
      lower: 0.0
      upper: inf
  sersic_index:
    type: Uniform
    lower_limit: 0.8
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: 0.8
      upper: 5.0
